name: Build and Deploy demo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        echo Installing dependencies ...
        npm install
        echo Building demo ...
        npm run build-demo
    -
      name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: demo
      env:
        GITHUB_PAT: ${{ secrets.GHPAGES_PAT }}
