name: Build and NPM Publish

on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0
    - name: Build
      run: |
        echo Installing dependencies ...
        npm install
        echo Building ...
        npm run build
    - name: Publish version
      uses: geoblink/publish-to-npm@v1.0.2
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM }} # You must set this in your repo settings
